name: 02-TruffleHog-Security-Scan
on:
  pull_request_target:
    types: [opened, synchronize, edited]

  workflow_dispatch:

jobs:
  trufflehog_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout fork repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.user.login }}/${{ github.event.repository.name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.84.0
      with:
        extra_args: --only-verified
